- name: nginx
  community.docker.docker_container:
    name: nginx
    image: "{{ images.nginx }}"
    container_default_behavior: no_defaults
    log_driver: "json-file"
    log_options: "max-size=5m"
    capabilities: "NET_ADMIN"
    network_mode: "host"
    ports:
      - '80:80'