- name: Dependencies
  become: true
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: add GPG key
  become: true
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: add docker repository to apt
  become: true
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu noble stable
    state: present


- name: Docker install
  become: true
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin



